# Display a picture of Beep the robot
print("\n")
print("   ###########")
print("# # (O  /  O) # #")
print("# #      /    # #")
print("   ###########")
print("\t  #####")
print("   ###########")
print("  #  # --- #  #")
print(" #   #o..  #   #")
print(" #   #     #   #")
print("  #  #     #  #")
print("   ###########")
print("\n")